// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using bobbybots_backend;

namespace bobbybots_backend.Migrations
{
    [DbContext(typeof(BotContext))]
    partial class BotContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079");

            modelBuilder.Entity("bobbybots_backend.entity.Category", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.Property<string>("RobotId");

                    b.HasKey("Id");

                    b.HasIndex("RobotId");

                    b.ToTable("Category");
                });

            modelBuilder.Entity("bobbybots_backend.entity.Robot", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Image");

                    b.Property<string>("Name");

                    b.Property<int>("Score");

                    b.HasKey("Id");

                    b.ToTable("Bots");
                });

            modelBuilder.Entity("bobbybots_backend.entity.Category", b =>
                {
                    b.HasOne("bobbybots_backend.entity.Robot")
                        .WithMany("Categories")
                        .HasForeignKey("RobotId");
                });
#pragma warning restore 612, 618
        }
    }
}
